build:
    maxIssues: 1000
    excludeCorrectable: true
    weights:
    # complexity: 2
    # LongParameterList: 1
    # style: 1
    # comments: 1

complexity:
    active: true
    ComplexCondition:
        active: true
        threshold: 10
    CyclomaticComplexMethod:
        active: true
        threshold: 30
    LongMethod:
        active: true
        threshold: 150
    LongParameterList:
        active: true
        constructorThreshold: 20
        functionThreshold: 20
    TooManyFunctions:
        active: true
        thresholdInFiles: 60
        thresholdInClasses: 50
    NestedBlockDepth:
        active: true
        threshold: 10

naming:
    active: true
    ClassNaming:
        active: true
        classPattern: '[A-Z][a-zA-Z0-9]*'
    FunctionNaming:
        active: true
        functionPattern: '^([a-z][a-zA-Z0-9]*)|(`.*`)$'
    VariableNaming:
        active: true
        variablePattern: '[a-z][a-zA-Z0-9]*'

style:
    active: true
    MagicNumber:
        active: false
        ignoreNumbers: [ '-1', '0', '1', '2', '10', '100', '1024' ]
    MaxLineLength:
        active: true
        maxLineLength: 300
    UnusedImports:
        active: true
    WildcardImport:
        active: false

potential-bugs:
    active: true
    UnsafeCallOnNullableType:
        active: true
    LateinitUsage:
        active: true
        ignoreAnnotated: [ 'Inject' ]

performance:
    active: true
    SpreadOperator:
        active: true
    UnnecessaryTemporaryInstantiation:
        active: true

formatting:
    active: true
    android: false
    autoCorrect: true
    continuationIndentSize: 8
    indentSize: 4
    maxLineLength: 120
